spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.113.128
    port: 5678
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1000000 #毫秒
#设置rabbitmq连接参数
  rabbitmq:
    host: 192.168.113.128
    username: guest
    password: guest