spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
